class ShampooRunner{
public static void main(String[] carWash){
Shampoo ref=new Shampoo();
ref.brandName="head&shoulder";
ref.qty= "3ml";
ref.type= "silky";
ref.price= 80;
ref.mfgDate= "12/7/24";
ref.expDate="14/9/26" ;

System.out.println("the brand name is "+ref.brandName);
System.out.println("the qty is "+ref.qty);
System.out.println("the type is "+ref.type);
System.out.println("the price is "+ref.price);
System.out.println("the mfg is "+ref.mfgDate);
System.out.println("the expDate is "+ref.expDate);
System.out.println("..............................");
Shampoo ref1=new Shampoo();
ref1.brandName="kartika";
ref1.qty= "6ml";
ref1.type= "smoothy";
ref1.price= 20;
ref1.mfgDate= "23/6/24";
ref1.expDate="8/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref1.brandName);
System.out.println("the qty is "+ref1.qty);
System.out.println("the type is "+ref1.type);
System.out.println("the price is "+ref1.price);
System.out.println("the mfg is "+ref1.mfgDate);
System.out.println("the expDate is "+ref1.expDate);

Shampoo ref2=new Shampoo();
ref2.brandName="nyle";
ref2.qty= "2ml";
ref2.type= "shynyy";
ref2.price= 100;
ref2.mfgDate= "23/2/24";
ref2.expDate="33/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref2.brandName);
System.out.println("the qty is "+ref2.qty);
System.out.println("the type is "+ref2.type);
System.out.println("the price is "+ref2.price);
System.out.println("the mfg is "+ref2.mfgDate);
System.out.println("the expDate is "+ref2.expDate);
Shampoo ref3=new Shampoo();
ref3.brandName="garneir";
ref3.qty= "2ml";
ref3.type= "curl defining";
ref3.price= 20;
ref3.mfgDate= "5/2/23";
ref3.expDate="12/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref3.brandName);
System.out.println("the qty is "+ref3.qty);
System.out.println("the type is "+ref3.type);
System.out.println("the price is "+ref3.price);
System.out.println("the mfg is "+ref3.mfgDate);
System.out.println("the expDate is "+ref3.expDate);

Shampoo ref4=new Shampoo();
ref4.brandName="cbotique";
ref4.qty= "8ml";
ref4.type= "straightning";
ref4.price= 899;
ref4.mfgDate= "12/2/24";
ref4.expDate="6/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref4.brandName);
System.out.println("the qty is "+ref4.qty);
System.out.println("the type is "+ref4.type);
System.out.println("the price is "+ref4.price);
System.out.println("the mfg is "+ref4.mfgDate);
System.out.println("the expDate is "+ref4.expDate);
Shampoo ref5=new Shampoo();
ref5.brandName="dabour";
ref5.qty= "2ml";
ref5.type= "oily";
ref5.price= 20;
ref5.mfgDate= "12/2/24";
ref5.expDate="12/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref5.brandName);
System.out.println("the qty is "+ref5.qty);
System.out.println("the type is "+ref5.type);
System.out.println("the price is "+ref5.price);
System.out.println("the mfg is "+ref5.mfgDate);
System.out.println("the expDate is "+ref5.expDate);

Shampoo ref6=new Shampoo();
ref6.brandName="axe";
ref6.qty= "9ml";
ref6.type= "oily";
ref6.price= 20;
ref6.mfgDate= "12/2/24";
ref6.expDate="12/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref6.brandName);
System.out.println("the qty is "+ref6.qty);
System.out.println("the type is "+ref6.type);
System.out.println("the price is "+ref6.price);
System.out.println("the mfg is "+ref6.mfgDate);
System.out.println("the expDate is "+ref6.expDate);

Shampoo ref7=new Shampoo();
ref7.brandName="biotic";
ref7.qty= "8ml";
ref7.type= "healthy hair";
ref7.price= 78;
ref7.mfgDate= "29/9/23";
ref7.expDate="7/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref7.brandName);
System.out.println("the qty is "+ref7.qty);
System.out.println("the type is "+ref7.type);
System.out.println("the price is "+ref7.price);
System.out.println("the mfg is "+ref7.mfgDate);
System.out.println("the expDate is "+ref7.expDate);

Shampoo ref8=new Shampoo();
ref8.brandName="denver";
ref8.qty= "2ml";
ref8.type= "super silky";
ref8.price= 20;
ref8.mfgDate= "16/2/24";
ref8.expDate="12/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref8.brandName);
System.out.println("the qty is "+ref8.qty);
System.out.println("the type is "+ref8.type);
System.out.println("the price is "+ref8.price);
System.out.println("the mfg is "+ref8.mfgDate);
System.out.println("the expDate is "+ref8.expDate);

Shampoo ref9=new Shampoo();
ref9.brandName="clinic";
ref9.qty= "2ml";
ref9.type= "oily";
ref9.price= 20;
ref9.mfgDate= "12/2/24";
ref9.expDate="12/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref9.brandName);
System.out.println("the qty is "+ref9.qty);
System.out.println("the type is "+ref9.type);
System.out.println("the price is "+ref9.price);
System.out.println("the mfg is "+ref9.mfgDate);
System.out.println("the expDate is "+ref9.expDate);

Shampoo ref12=new Shampoo();
ref12.brandName="clinic";
ref12.qty= "2ml";
ref12.type= "oily";
ref12.price= 20;
ref12.mfgDate= "12/2/24";
ref12.expDate="12/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref12.brandName);
System.out.println("the qty is "+ref12.qty);
System.out.println("the type is "+ref12.type);
System.out.println("the price is "+ref12.price);
System.out.println("the mfg is "+ref12.mfgDate);
System.out.println("the expDate is "+ref12.expDate);

Shampoo ref13=new Shampoo();
ref13.brandName="clinic";
ref13.qty= "2ml";
ref13.type= "oily";
ref13.price= 20;
ref13.mfgDate= "12/2/24";
ref13.expDate="12/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref13.brandName);
System.out.println("the qty is "+ref13.qty);
System.out.println("the type is "+ref13.type);
System.out.println("the price is "+ref13.price);
System.out.println("the mfg is "+ref13.mfgDate);
System.out.println("the expDate is "+ref13.expDate);

Shampoo ref14=new Shampoo();
ref14.brandName="ayurvedic";
ref14.qty= "2ml";
ref14.type= "oily";
ref14.price= 20;
ref14.mfgDate= "12/2/24";
ref14.expDate="12/8/24" ;
System.out.println("..............................");
System.out.println("the brand name is "+ref14.brandName);
System.out.println("the qty is "+ref14.qty);
System.out.println("the type is "+ref14.type);
System.out.println("the price is "+ref14.price);
System.out.println("the mfg is "+ref14.mfgDate);
System.out.println("the expDate is "+ref14.expDate);
}
}